import path from "node:path";
import { DatabaseSync } from "node:sqlite";
import type { Routine, RoutineInput } from "./routines";

/**
 * Durable storage for the runtime, backed by SQLite (Node's built-in
 * `node:sqlite` — no native dependency to compile). For now it holds a
 * task-completion log so observability survives restarts; the helpers are
 * parameterized by a `DatabaseSync` so they can be unit-tested against an
 * in-memory database.
 */

const DB_FILE = path.join(process.cwd(), ".sams-data.db");

export interface TaskLogEntry {
  agentId: string;
  agentName: string;
  title: string;
  branch: string;
  status: string;
  tokens: number;
  ts: number;
}

export interface TaskStats {
  total: number;
  completed: number;
  tokens: number;
}

/** Open (and migrate) a database at `location`. Use ":memory:" in tests. */
export function openDb(location: string): DatabaseSync {
  const db = new DatabaseSync(location);
  db.exec(`
    CREATE TABLE IF NOT EXISTS task_log (
      id         INTEGER PRIMARY KEY AUTOINCREMENT,
      agent_id   TEXT    NOT NULL,
      agent_name TEXT    NOT NULL,
      title      TEXT    NOT NULL,
      branch     TEXT    NOT NULL,
      status     TEXT    NOT NULL,
      tokens     INTEGER NOT NULL DEFAULT 0,
      ts         INTEGER NOT NULL
    );
    CREATE INDEX IF NOT EXISTS idx_task_log_ts ON task_log (ts DESC);

    CREATE TABLE IF NOT EXISTS agent_memory (
      agent_id   TEXT    NOT NULL,
      key        TEXT    NOT NULL,
      value      TEXT    NOT NULL,
      updated_at INTEGER NOT NULL,
      PRIMARY KEY (agent_id, key)
    );

    CREATE TABLE IF NOT EXISTS routines (
      id           TEXT    PRIMARY KEY,
      name         TEXT    NOT NULL,
      title        TEXT    NOT NULL,
      branch       TEXT    NOT NULL DEFAULT '',
      kind         TEXT    NOT NULL,
      interval_min INTEGER NOT NULL DEFAULT 60,
      at_hour      INTEGER NOT NULL DEFAULT 9,
      at_min       INTEGER NOT NULL DEFAULT 0,
      enabled      INTEGER NOT NULL DEFAULT 1,
      last_run     INTEGER NOT NULL DEFAULT 0,
      created_at   INTEGER NOT NULL
    );
  `);
  return db;
}

// --- routine helpers (trigger temporali) -----------------------------------

function rowToRoutine(r: Record<string, unknown>): Routine {
  return {
    id: String(r.id),
    name: String(r.name),
    title: String(r.title),
    branch: String(r.branch ?? ""),
    kind: r.kind === "daily" ? "daily" : "interval",
    intervalMin: Number(r.interval_min),
    atHour: Number(r.at_hour),
    atMin: Number(r.at_min),
    enabled: Number(r.enabled) !== 0,
    lastRun: Number(r.last_run),
  };
}

/** All routines, oldest first. */
export function listRoutines(db: DatabaseSync): Routine[] {
  const rows = db.prepare(`SELECT * FROM routines ORDER BY created_at ASC`).all() as Record<string, unknown>[];
  return rows.map(rowToRoutine);
}

/** Insert a new routine (id generated by the caller) and return it. */
export function insertRoutine(db: DatabaseSync, id: string, input: RoutineInput): Routine {
  db.prepare(
    `INSERT INTO routines (id, name, title, branch, kind, interval_min, at_hour, at_min, enabled, last_run, created_at)
     VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, 0, ?)`,
  ).run(
    id,
    input.name,
    input.title,
    input.branch,
    input.kind,
    input.intervalMin,
    input.atHour,
    input.atMin,
    input.enabled ? 1 : 0,
    Date.now(),
  );
  return { ...input, id, lastRun: 0 };
}

export function deleteRoutine(db: DatabaseSync, id: string): void {
  db.prepare(`DELETE FROM routines WHERE id = ?`).run(id);
}

export function setRoutineEnabled(db: DatabaseSync, id: string, enabled: boolean): void {
  db.prepare(`UPDATE routines SET enabled = ? WHERE id = ?`).run(enabled ? 1 : 0, id);
}

/** Stamp the last-run time (called by the scheduler when a routine fires). */
export function markRoutineRun(db: DatabaseSync, id: string, ts: number): void {
  db.prepare(`UPDATE routines SET last_run = ? WHERE id = ?`).run(ts, id);
}

// --- agent memory helpers ---------------------------------------------------

export interface MemoryEntry { key: string; value: string; updatedAt: number }

export function setMemory(db: DatabaseSync, agentId: string, key: string, value: string): void {
  db.prepare(
    `INSERT INTO agent_memory (agent_id, key, value, updated_at) VALUES (?, ?, ?, ?)
     ON CONFLICT (agent_id, key) DO UPDATE SET value = excluded.value, updated_at = excluded.updated_at`,
  ).run(agentId, key.slice(0, 100), value.slice(0, 2000), Date.now());
}

export function getMemory(db: DatabaseSync, agentId: string, key: string): string | null {
  const row = db.prepare(`SELECT value FROM agent_memory WHERE agent_id = ? AND key = ?`).get(agentId, key) as
    | { value: string } | undefined;
  return row?.value ?? null;
}

export function listMemory(db: DatabaseSync, agentId: string): MemoryEntry[] {
  return (db.prepare(
    `SELECT key, value, updated_at AS updatedAt FROM agent_memory WHERE agent_id = ? ORDER BY updated_at DESC LIMIT 30`,
  ).all(agentId) as unknown as MemoryEntry[]).map((r) => ({ ...r, updatedAt: Number(r.updatedAt) }));
}

export function clearMemory(db: DatabaseSync, agentId: string): void {
  db.prepare(`DELETE FROM agent_memory WHERE agent_id = ?`).run(agentId);
}

/** Append one finished task to the log. */
export function insertTask(db: DatabaseSync, e: TaskLogEntry): void {
  db.prepare(
    `INSERT INTO task_log (agent_id, agent_name, title, branch, status, tokens, ts)
     VALUES (?, ?, ?, ?, ?, ?, ?)`,
  ).run(e.agentId, e.agentName, e.title, e.branch, e.status, e.tokens, e.ts);
}

/** Most recent tasks, newest first. */
export function recentTasks(db: DatabaseSync, limit = 20): TaskLogEntry[] {
  const rows = db
    .prepare(
      `SELECT agent_id AS agentId, agent_name AS agentName, title, branch, status, tokens, ts
       FROM task_log ORDER BY ts DESC LIMIT ?`,
    )
    .all(limit) as unknown as TaskLogEntry[];
  return rows.map((r) => ({ ...r, tokens: Number(r.tokens), ts: Number(r.ts) }));
}

/** Cumulative counts across the whole log. */
export function taskStats(db: DatabaseSync): TaskStats {
  const row = db
    .prepare(
      `SELECT COUNT(*) AS total,
              SUM(CASE WHEN status IN ('review', 'done') THEN 1 ELSE 0 END) AS completed,
              COALESCE(SUM(tokens), 0) AS tokens
       FROM task_log`,
    )
    .get() as { total: number; completed: number | null; tokens: number };
  return { total: Number(row.total), completed: Number(row.completed ?? 0), tokens: Number(row.tokens) };
}

// --- lazy singleton (file-backed) ------------------------------------------
let _db: DatabaseSync | null = null;

/** The shared file-backed database, opened on first use. */
export function db(): DatabaseSync {
  if (!_db) _db = openDb(DB_FILE);
  return _db;
}

/** Best-effort append of a finished task to the durable log (never throws). */
export function logTask(e: TaskLogEntry): void {
  try {
    insertTask(db(), e);
  } catch (err) {
    console.warn("task log write failed:", (err as Error).message);
  }
}
